### ISSUE TITLE
error authentification

### ISSUE THREAD

**Issue by msirisak** [tareqmamari/openwhisk-package-iotRTInsights#1]
Hi, 
I have an autentification error when I try to create an rti feed. However I am quite sure I put the right API key and token for my RTI service on Bluemix, and I also set my openwisk property to my organisation. Can you tell me what i did wrong or if I miss something? 
Thanks a lot,

![image](https://cloud.githubusercontent.com/assets/19287309/16409089/1de014e8-3d1c-11e6-9418-27a45a535cdd.png)

**Comment by tareqmamari** [comment]
Hi, RTI package is not yet added into openwhisk, we are currently in the process to achieve that. For now, you may need to create the feed action manually. To do that please follow the following steps:

```
#Download the webhook.js
wget https://raw.githubusercontent.com/tareqmamari/openwhisk-package-iotRTInsights/master/iot-rti/webhook.js

#Create a feed action (webhook) as any normal action
wsk action create rtiWebhook webhook.js

#Use the created webhook as a feed to the trigger
wsk trigger create rtiListener --feed rtiWebhook -p apiKey "" ...

```

**Comment by msirisak** [comment]
It works, Thanks !
